### ISSUE TITLE
Add function

### ISSUE THREAD

**Issue by JoergSH** [bertmelis/esp32WS2811#2]
Hi,
nice lib.
Could You add a function to change only R or G or B.

somthing like .setR(n,255);

regards
Joerg

**Comment by bertmelis** [comment]
Sure.

Meanwhile, you can workaround using get and set.

**Comment by bertmelis** [comment]
Like #3 ?

**Comment by JoergSH** [comment]
Yeah I like it!!!!
works great!
I use the ws2811 as a cheap led driver for "single" LEDs 
thanks a lot

**Comment by bertmelis** [comment]
Happy to help.
